### ISSUE TITLE
Decide whether to keep the `*.c` files or not...

### ISSUE THREAD

**Issue by saullocastro** [saullocastro/cubature#10]
@antonl  I created this issue to track conversations regarding this decision.

If we find out it will be tricky to keep the `*.c` compatible with different Python versions, I think we should remove them...

**Comment by antonl** [comment]
Yes, I'd prefer not to keep them under version control. Switching branches and commits is really annoying right now because git complains about modifications to a huge file. Instead, I think we can generate these files for releases and have people download those instead of cloning master. I think it is not unreasonable to expect that if somebody clones the repo they should have the tools to build the package installed.

**Comment by saullocastro** [comment]
Good Idea, I'll remove the `*.c` files
