### ISSUE TITLE
import cubature error

### ISSUE THREAD

**Issue by amrit-poudel** [saullocastro/cubature#8]
I get the following error when I try to import cubature.

ImportError: /home/somedir/.python-eggs/cubature-0.13.0.dev0-py2.7-linux-x86_64.egg-tmp/cubature/_cubature.so: undefined symbol: hcubature

I import cubature like this:

from cubature import cubature

Then, I use it in the following way:

out = cubature(func, ndim, fdim, xmin, xmax, args=(wd, widthd, wa, widtha), vectorized=True)  
	           

I do not understand why I get that error.

Thanks for your help.

**Comment by amrit-poudel** [comment]
I could not fix this error. Could  you help what is going on here?

**Comment by saullocastro** [comment]
@amrit-poudel  Cython is not needed to import, only to convert the .pyx to .c.

Could you please paste here the script you're trying to run? I will be glad to check that for you.

**Comment by amrit-poudel** [comment]
That for the reply. I am not running any script.

When I type  import cubature I get this following error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/cubature/__init__.py", line 3, in <module>
  File "build/bdist.linux-x86_64/egg/cubature/cubature.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/cubature/_cubature.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/cubature/_cubature.py", line 6, in __bootstrap__
ImportError: /public/home/somedir/.python-eggs/cubature-0.13.0.dev0-py2.7-linux-x86_64.egg-tmp/cubature/_cubature.so: undefined symbol: hcubature

**Comment by saullocastro** [comment]
@amrit-poudel   I can import the module here without problems. I just submitted a small bug correction that might be the reason for your import error. Could you please update your local repository and try again?

**Comment by amrit-poudel** [comment]
I did  that, but I still cannot import the cubature!!

**Comment by saullocastro** [comment]
I'm trying to fix here

**Comment by saullocastro** [comment]
@amrit-poudel  I just submitted another commit. I hope it will work now

**Comment by amrit-poudel** [comment]
It does not work!

**Comment by saullocastro** [comment]
Could you please make a test:
- compile with `python setup.py build_ext --inplace clean`. This will compile where the downloaded repository is.
- Then, open python in the root folder of this repository. Do:

    import cubature
    execfile('./examples/ex_volumes.py')

I want to see if there is something tricky with python setup.py install.

Cheers

**Comment by amrit-poudel** [comment]
Nope! Did not work-- same error.

cubature-master is the directory where I have the source code.

cd cubature-master
 python setup.py build_ext --inplace clean

Then, from the same folder I called
python
>> import cubature

ImportError: cubature/_cubature.so: undefined symbol: hcubature

**Comment by antonl** [comment]
@saullocastro Do you use python 2.7? 

The reason I ask is that when I pulled your master a few minutes ago, I also could not execute ```build_inplace```. After deleting the ```*.c``` files and re-```cython```izing them the build completed and it passed all of the unit-tests. 

@amrit-poudel not that it should matter, but what versions of cython, python are you using?

**Comment by amrit-poudel** [comment]
@antonl  I do not have cython installed (but I can install if that is required for cubature, but I was told it is not required to import cubature). I am using python 2.7.

**Comment by saullocastro** [comment]
@antonl I do have Python 2.7, but 64-Bit, and running on Windows.... perhaps it will be a good idea to remove all the `*.c`

**Comment by antonl** [comment]
It shouldn't be required, but I wonder if the code that cython generates is different on python 2.7 vs python 3.4.

I made a virtual environment with python 2.7, cython and pytest and tried running build-inplace. Because I had just built everything for python 3.4, I did not need to cythonize I also could not get it to work, though my error was different (I'm on OS X)
```
    import cubature._test_integrands as ti
cubature/__init__.py:40: in <module>
    from .cubature import *
cubature/cubature.py:2: in <module>
    from ._cubature import cubature as _cython_cubature
E   ImportError: dlopen(/Users/aloukian/Documents/cubature/cubature/_cubature.so, 2): Symbol not found: _PyBytes_Type
E     Referenced from: /Users/aloukian/Documents/cubature/cubature/_cubature.so
E     Expected in: dynamic lookup
```
After that, I tried removing the ```*.c``` files and redoing build-inplace. Stuff compiles now, but I get unit-test failures for the genz-oscillatory test. This is very troubling. 

Is there a chance that @amrit-poudel could try installing cython and running things? I would suggest installing anaconda (into your local folder if you don't have admin permissions) and then adding conda to your PATH. You can install the miniconda distribution if internet bandwidth is an issue. Then I would run something like
```bash
$ conda create -n cubature-py27 python=2.7 cython
$ source activate cubature-py27
$ pip install pytest 
... go to your cubature clone
$ rm cubature/_cubature.c cubature/_test_integrands.c
$ python setup.py build_ext --inplace
$ py.test (or python -m pytest)
```

**Comment by saullocastro** [comment]
@amrit-poudel  I found some discussions about this like:

http://stackoverflow.com/q/23391144/832621

but I believe @antonl 's suggestion is the best option. Try to install Cython in your Linux system and create the `.c` files.

@antonl  here I also have 4 functions failing the test...

**Comment by antonl** [comment]
I am running python 3.4 and have all tests passing. Upon switching to 2.7, I get some failing tests, but I suspect that the problem is really dumb - python 3 has floating point division by default, and I've stopped including ```from __future__ import division```.

One noticeable thing is the that the unit tests run significantly slower than before, about four times slower. To compare, I checked out the branch right upon merging #4. I still get the failing tests, but the whole run takes 146 s (vs 516s @584e06b). We should create a new issue for this. 

I did notice that upon compiling the cython code gives new warnings now:
```
warning: cubature/_cubature.pxd:16:17: Function signature does not match previous declaration
warning: cubature/_cubature.pxd:21:17: Function signature does not match previous declaration
warning: cubature/_cubature.pxd:26:19: Function signature does not match previous declaration
warning: cubature/_cubature.pxd:31:19: Function signature does not match previous declaration
warning: cubature/_cubature.pxd:43:23: Function signature does not match previous declaration
```

@saullocastro did commit #6 change the call signature of hcubature?

**Comment by saullocastro** [comment]
These warnings are just due to an include I put there trying to solve the
import error reported in this issue.

About the slowness. I posted a SO answer that explains the mutual
dependency between future __division__ and Cython cdivision directive. We
should stick to the latter only.

**Comment by saullocastro** [comment]
@antonl This is the SO answer I mentioned above
http://stackoverflow.com/a/23887259/832621

**Comment by amrit-poudel** [comment]
I installed cython (version 0.22), put that on $PYTHONPATH and then installed cubature. I did not install anaconda-- it is too clunky.

Then I built cubature package following the standard build-install sequence:

python setup.py build 
python setup.py --prefix=/whereverIwant


Finally, I was able to import cubature without that ugly error I encountered before.

Next, I would not like to test some cubature examples, but I don't have pytest installed (I only have nose, which I think is pretty good). I will just copy paste test code and run them.

**Comment by saullocastro** [comment]
@amrit-poudel  thanks for the update, I recommend you adding a new issue for this question regarding the memory error. We can check that

**Comment by saullocastro** [comment]
Solved by removing the distrubuted `*.c` files https://github.com/saullocastro/cubature/issues/10

**Comment by antonl** [comment]
@amrit-poudel cubature is almost certainly is not giving you the right answer. Are you integrating a particularly oscillatory function, or is your tolerance set too high? 

Although I think it should be straightforward to install pytest into your environment (```pip install pytest```), I recently pushed a commit (@cc289f3de) that allows you to use ```nosetests``` to run the testsuite. Turns out they're compatible, as long as we don't use any pytest-specific functionality.

**Comment by amrit-poudel** [comment]
I am integrating oscillatory multivariate integral. I will open new thread if i cannot resolve it myself.

@antonl, I have only tested using execfile('./examples/ex_volumes.py') and these simple tests passed. I have not tested other cases. 

I will try to copy the updated test files and run the test cases, w/o installing pytest (I don't have anything against pytest--it is  just that I don't want to install too many packages).

**Comment by antonl** [comment]
What I meant was that nosetests works now as well as pytest. You should be able to just pull the current master and run ```nosetests``` in the directory containing the ```test_*.py``` files. This will run the unit tests that we already have.
